plugins: [jekyll-paginate]

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: "page/:num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js]



title: "Prakash"
email: pranphy@gmail.com
description: ""
github:
  username: pranphy
swiftype:
  searchId: 
gitment:
    repo: blog
    client_id: 
    client_secret: 

url: "https://pranphy.github.io/"
imgrepo: "https://pranphy.github.io/static/img"


#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

