plugins: [jekyll-paginate]

permalink: /blog/:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: "/blog/page/:num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js]

name:
    default: Prakash
    alternate: प्रकाश

title: "Prakash"
email: pranphy@gmail.com
description: ""
github:
  username: pranphy
social:
    github: pranphy
    facebook: pranphy
    twitter: pranphy
    gmail: pranphy


swiftype:
  searchId: 
gitment:
    repo: pranphy.github.io
    client_id: 9018c93d90caaeb61b82
    client_secret: 9718765fb4f4cb8cd84403467b9e4504882282d4

url: "https://pranphy.github.io"
imgrepo: "https://pranphy.github.io/static/img"


#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

